import json
import os
import sys
import time
import urllib.error
import urllib.request
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

MODE=os.environ.get("GATEWAY_MODE","MOCK").upper()
LOCAL_TOKEN=os.environ.get("LOCAL_TOKEN","")
UPSTREAM_BASE_URL=os.environ.get("UPSTREAM_BASE_URL","").rstrip("/")
UPSTREAM_API_KEY=os.environ.get("UPSTREAM_API_KEY","")
MAX_BODY=2*1024*1024

BUILD_COMMAND=r"""mkdir -p artifact tests
cat > artifact/main.py <<'PY'
def quote_price(monthly_usd: float) -> float:
    if monthly_usd < 0:
        raise ValueError("monthly_usd must be non-negative")
    return round(monthly_usd * 12, 2)
PY
cat > artifact/README.md <<'MD'
# OpenHands Sandbox Artifact

Generated by OpenHands inside the isolated AI Digital Asset Factory workspace.
MD
cat > tests/test_artifact.py <<'PY'
import importlib.util
import pathlib
import unittest

path=pathlib.Path("/workspace/artifact/main.py")
spec=importlib.util.spec_from_file_location("artifact_main", path)
mod=importlib.util.module_from_spec(spec)
spec.loader.exec_module(mod)

class ArtifactTest(unittest.TestCase):
    def test_quote_price(self):
        self.assertEqual(mod.quote_price(25), 300)

    def test_negative_rejected(self):
        with self.assertRaises(ValueError):
            mod.quote_price(-1)

if __name__ == "__main__":
    unittest.main()
PY
printf 'OPENHANDS_ARTIFACT_CREATED\n'
"""

class Handler(BaseHTTPRequestHandler):
    mock_calls=0

    def log_message(self, fmt, *args):
        print("[gateway] "+(fmt % args), file=sys.stderr, flush=True)

    def _json(self,status,payload):
        data=json.dumps(payload).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type","application/json")
        self.send_header("Content-Length",str(len(data)))
        self.end_headers()
        self.wfile.write(data)

    def _auth_ok(self):
        if not LOCAL_TOKEN:
            return False
        return self.headers.get("Authorization","")==f"Bearer {LOCAL_TOKEN}"

    def do_GET(self):
        if self.path.rstrip("/") in ("","/health"):
            self._json(200,{"status":"ok","mode":MODE})
            return
        self._json(404,{"error":"not_found"})

    def do_POST(self):
        if not self._auth_ok():
            self._json(401,{"error":{"message":"invalid local gateway token","type":"invalid_api_key"}})
            return
        path=self.path.split("?",1)[0]
        if path not in ("/v1/chat/completions","/chat/completions","/completions"):
            self._json(404,{"error":{"message":"unsupported path","type":"not_found"}})
            return
        try:
            length=int(self.headers.get("Content-Length","0"))
        except ValueError:
            length=0
        if length<0 or length>MAX_BODY:
            self._json(413,{"error":{"message":"request too large","type":"invalid_request_error"}})
            return
        raw=self.rfile.read(length)
        try:
            body=json.loads(raw or b"{}")
        except json.JSONDecodeError:
            self._json(400,{"error":{"message":"invalid json","type":"invalid_request_error"}})
            return
        if MODE=="MOCK":
            self._mock(body)
        elif MODE=="PROXY":
            self._proxy(raw)
        else:
            self._json(500,{"error":{"message":"invalid gateway mode","type":"server_error"}})

    def _is_ping(self,body):
        if body.get("max_tokens")!=1:
            return False
        msgs=body.get("messages")
        if not isinstance(msgs,list) or len(msgs)!=1:
            return False
        content=msgs[0].get("content") if isinstance(msgs[0],dict) else None
        if isinstance(content,list):
            content="".join(
                p.get("text","") for p in content
                if isinstance(p,dict) and p.get("type")=="text"
            )
        return isinstance(content,str) and content.strip()=="ping"

    def _mock_message(self,body):
        model=body.get("model") or "mock"
        if self._is_ping(body):
            return {
                "id":"chatcmpl-ping","object":"chat.completion","created":int(time.time()),
                "model":model,
                "choices":[{"index":0,"message":{"role":"assistant","content":"pong"},"finish_reason":"stop"}],
                "usage":{"prompt_tokens":1,"completion_tokens":1,"total_tokens":2},
            }
        Handler.mock_calls+=1
        if Handler.mock_calls==1:
            message={
                "role":"assistant",
                "content":"",
                "tool_calls":[{
                    "id":"call_asset_factory_001",
                    "type":"function",
                    "function":{"name":"terminal","arguments":json.dumps({
                        "security_risk":"LOW",
                        "summary":"Create isolated sandbox artifact and tests",
                        "command":BUILD_COMMAND,
                    })},
                }],
            }
            finish="tool_calls"
        else:
            message={"role":"assistant","content":"OPENHANDS_SANDBOX_BUILD_COMPLETE"}
            finish="stop"
        return {
            "id":f"chatcmpl-mock-{Handler.mock_calls}",
            "object":"chat.completion",
            "created":int(time.time()),
            "model":model,
            "choices":[{"index":0,"message":message,"finish_reason":finish}],
            "usage":{"prompt_tokens":20,"completion_tokens":10,"total_tokens":30},
        }

    def _mock(self,body):
        payload=self._mock_message(body)
        if not body.get("stream"):
            self._json(200,payload)
            return
        choice=payload["choices"][0]
        msg=choice["message"]
        base={
            "id":payload["id"],
            "object":"chat.completion.chunk",
            "created":payload["created"],
            "model":payload["model"],
        }
        chunks=[]
        if msg.get("tool_calls"):
            chunks.append({**base,"choices":[{"index":0,"delta":{"role":"assistant"},"finish_reason":None}]})
            for idx,tc in enumerate(msg["tool_calls"]):
                fn=tc["function"]
                chunks.append({**base,"choices":[{"index":0,"delta":{"tool_calls":[{
                    "index":idx,"id":tc["id"],"type":"function",
                    "function":{"name":fn["name"],"arguments":""},
                }]},"finish_reason":None}]})
                if fn.get("arguments"):
                    chunks.append({**base,"choices":[{"index":0,"delta":{"tool_calls":[{
                        "index":idx,
                        "function":{"arguments":fn["arguments"]},
                    }]},"finish_reason":None}]})
        else:
            chunks.append({**base,"choices":[{"index":0,"delta":{"role":"assistant","content":msg.get("content","")},"finish_reason":None}]})
        chunks.append({**base,"choices":[{"index":0,"delta":{},"finish_reason":choice["finish_reason"]}]})
        self.send_response(200)
        self.send_header("Content-Type","text/event-stream")
        self.send_header("Cache-Control","no-cache")
        self.end_headers()
        for chunk in chunks:
            self.wfile.write(("data: "+json.dumps(chunk)+"\n\n").encode("utf-8"))
        if (body.get("stream_options") or {}).get("include_usage"):
            usage={**base,"choices":[],"usage":payload.get("usage") or {
                "prompt_tokens":20,"completion_tokens":10,"total_tokens":30
            }}
            self.wfile.write(("data: "+json.dumps(usage)+"\n\n").encode("utf-8"))
        self.wfile.write(b"data: [DONE]\n\n")
        self.wfile.flush()

    def _proxy(self,raw):
        if not UPSTREAM_BASE_URL or not UPSTREAM_API_KEY:
            self._json(503,{"error":{"message":"upstream not configured","type":"server_error"}})
            return
        url=UPSTREAM_BASE_URL+"/chat/completions"
        req=urllib.request.Request(
            url,
            data=raw,
            headers={
                "Content-Type":"application/json",
                "Authorization":f"Bearer {UPSTREAM_API_KEY}",
            },
            method="POST",
        )
        try:
            with urllib.request.urlopen(req,timeout=120) as resp:
                data=resp.read()
                self.send_response(resp.status)
                self.send_header("Content-Type",resp.headers.get("Content-Type","application/json"))
                self.send_header("Content-Length",str(len(data)))
                self.end_headers()
                self.wfile.write(data)
        except urllib.error.HTTPError as exc:
            data=exc.read()
            self.send_response(exc.code)
            self.send_header("Content-Type",exc.headers.get("Content-Type","application/json"))
            self.send_header("Content-Length",str(len(data)))
            self.end_headers()
            self.wfile.write(data)
        except Exception as exc:
            self._json(502,{"error":{"message":str(exc),"type":"gateway_error"}})

if __name__=="__main__":
    port=int(os.environ.get("PORT","9999"))
    server=ThreadingHTTPServer(("0.0.0.0",port),Handler)
    print(f"OpenHands gateway ready on :{port} mode={MODE}",flush=True)
    server.serve_forever()
