import json
import math
import os
import sys
import threading
import time
import urllib.error
import urllib.request
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path

MODE=os.environ.get("GATEWAY_MODE","MOCK").upper()
LOCAL_TOKEN=os.environ.get("LOCAL_TOKEN","")
UPSTREAM_BASE_URL=os.environ.get("UPSTREAM_BASE_URL","").rstrip("/")
UPSTREAM_API_KEY=os.environ.get("UPSTREAM_API_KEY","")
MAX_BODY=2*1024*1024

ALLOWED_MODELS=[x.strip() for x in os.environ.get("ALLOWED_MODELS","").split(",") if x.strip()]
MAX_REQUESTS=int(os.environ.get("MAX_REQUESTS","8"))
MAX_PROMPT_TOKENS_PER_REQUEST=int(os.environ.get("MAX_PROMPT_TOKENS_PER_REQUEST","12000"))
MAX_COMPLETION_TOKENS_PER_REQUEST=int(os.environ.get("MAX_COMPLETION_TOKENS_PER_REQUEST","4000"))
MAX_TOTAL_TOKENS=int(os.environ.get("MAX_TOTAL_TOKENS","24000"))
MAX_COST_PER_REQUEST_USD=float(os.environ.get("MAX_COST_PER_REQUEST_USD","0.10"))
MAX_COST_USD=float(os.environ.get("MAX_COST_USD","0.25"))
INPUT_COST_PER_1M_USD=float(os.environ.get("INPUT_COST_PER_1M_USD","0"))
OUTPUT_COST_PER_1M_USD=float(os.environ.get("OUTPUT_COST_PER_1M_USD","0"))
AUDIT_FILE=Path(os.environ.get("AUDIT_FILE","/audit/usage.json"))

BUILD_COMMAND=r"""mkdir -p artifact tests
cat > artifact/main.py <<'PY'
def quote_price(monthly_usd: float) -> float:
    if monthly_usd < 0:
        raise ValueError("monthly_usd must be non-negative")
    return round(monthly_usd * 12, 2)
PY
cat > artifact/README.md <<'MD'
# OpenHands Sandbox Artifact

Generated by OpenHands inside the isolated AI Digital Asset Factory workspace.
MD
cat > tests/test_artifact.py <<'PY'
import importlib.util
import pathlib
import unittest

path=pathlib.Path("/workspace/artifact/main.py")
spec=importlib.util.spec_from_file_location("artifact_main", path)
mod=importlib.util.module_from_spec(spec)
spec.loader.exec_module(mod)

class ArtifactTest(unittest.TestCase):
    def test_quote_price(self):
        self.assertEqual(mod.quote_price(25), 300)

    def test_negative_rejected(self):
        with self.assertRaises(ValueError):
            mod.quote_price(-1)

if __name__ == "__main__":
    unittest.main()
PY
printf 'OPENHANDS_ARTIFACT_CREATED\n'
"""

def _model_aliases(value):
    value=(value or "").strip()
    if not value:
        return set()
    aliases={value}
    if "/" in value:
        aliases.add(value.split("/",1)[1])
    return aliases

def _allowed_model(requested, allowed):
    requested_aliases=_model_aliases(requested)
    if not requested_aliases:
        return False
    allowed_aliases=set()
    for item in allowed:
        allowed_aliases.update(_model_aliases(item))
    return bool(requested_aliases & allowed_aliases)

def _estimate_prompt_tokens(body):
    messages=body.get("messages") or []
    raw=json.dumps(messages,ensure_ascii=False,separators=(",",":"))
    return max(1,math.ceil(len(raw.encode("utf-8"))/3))

def _requested_completion_tokens(body):
    value=body.get("max_completion_tokens",body.get("max_tokens"))
    if value is None:
        return MAX_COMPLETION_TOKENS_PER_REQUEST
    try:
        return int(value)
    except (TypeError,ValueError):
        return MAX_COMPLETION_TOKENS_PER_REQUEST+1

def _cost(prompt_tokens,completion_tokens):
    return round(
        (prompt_tokens/1_000_000)*INPUT_COST_PER_1M_USD
        +(completion_tokens/1_000_000)*OUTPUT_COST_PER_1M_USD,
        9,
    )

def _usage_from_json(payload):
    usage=payload.get("usage") if isinstance(payload,dict) else None
    if not isinstance(usage,dict):
        return None
    prompt=int(usage.get("prompt_tokens") or usage.get("input_tokens") or 0)
    completion=int(usage.get("completion_tokens") or usage.get("output_tokens") or 0)
    total=int(usage.get("total_tokens") or (prompt+completion))
    return prompt,completion,total

def _usage_from_bytes(data,content_type):
    text=data.decode("utf-8",errors="replace")
    if "text/event-stream" in (content_type or "").lower() or text.lstrip().startswith("data:"):
        last=None
        for line in text.splitlines():
            line=line.strip()
            if not line.startswith("data:"):
                continue
            payload=line[5:].strip()
            if not payload or payload=="[DONE]":
                continue
            try:
                obj=json.loads(payload)
            except json.JSONDecodeError:
                continue
            usage=_usage_from_json(obj)
            if usage is not None:
                last=usage
        return last
    try:
        return _usage_from_json(json.loads(text))
    except json.JSONDecodeError:
        return None

class BudgetState:
    def __init__(self):
        self.lock=threading.Lock()
        self.request_count=0
        self.prompt_tokens=0
        self.completion_tokens=0
        self.total_tokens=0
        self.estimated_cost_usd=0.0
        self.blocked=False
        self.blocked_reason=""
        self.last_model=""
        self._persist()

    def snapshot(self):
        return {
            "mode":MODE,
            "budget_status":"BLOCKED" if self.blocked else "WITHIN_BUDGET",
            "request_count":self.request_count,
            "prompt_tokens":self.prompt_tokens,
            "completion_tokens":self.completion_tokens,
            "total_tokens":self.total_tokens,
            "estimated_cost_usd":round(self.estimated_cost_usd,9),
            "blocked":self.blocked,
            "blocked_reason":self.blocked_reason,
            "last_model":self.last_model,
            "limits":{
                "allowed_models":ALLOWED_MODELS,
                "max_requests":MAX_REQUESTS,
                "max_prompt_tokens_per_request":MAX_PROMPT_TOKENS_PER_REQUEST,
                "max_completion_tokens_per_request":MAX_COMPLETION_TOKENS_PER_REQUEST,
                "max_total_tokens":MAX_TOTAL_TOKENS,
                "max_cost_per_request_usd":MAX_COST_PER_REQUEST_USD,
                "max_cost_usd":MAX_COST_USD,
                "input_cost_per_1m_usd":INPUT_COST_PER_1M_USD,
                "output_cost_per_1m_usd":OUTPUT_COST_PER_1M_USD,
            },
        }

    def _persist(self):
        try:
            AUDIT_FILE.parent.mkdir(parents=True,exist_ok=True)
            tmp=AUDIT_FILE.with_suffix(".tmp")
            tmp.write_text(json.dumps(self.snapshot(),ensure_ascii=False,sort_keys=True),encoding="utf-8")
            os.replace(tmp,AUDIT_FILE)
        except OSError as exc:
            print(f"[gateway] audit persist failed: {exc}",file=sys.stderr,flush=True)

    def _block(self,reason):
        self.blocked=True
        self.blocked_reason=reason
        self._persist()
        return False,reason

    def preflight(self,body):
        if MODE!="PROXY":
            return True,"",None
        with self.lock:
            if self.blocked:
                return False,self.blocked_reason or "gateway already blocked",None
            model=str(body.get("model") or "").strip()
            self.last_model=model
            if not _allowed_model(model,ALLOWED_MODELS):
                ok,reason=self._block("model_not_allowed")
                return ok,reason,None
            if self.request_count>=MAX_REQUESTS:
                ok,reason=self._block("request_limit_exceeded")
                return ok,reason,None
            prompt_estimate=_estimate_prompt_tokens(body)
            completion_requested=_requested_completion_tokens(body)
            if prompt_estimate>MAX_PROMPT_TOKENS_PER_REQUEST:
                ok,reason=self._block("prompt_token_limit_exceeded")
                return ok,reason,None
            if completion_requested<1 or completion_requested>MAX_COMPLETION_TOKENS_PER_REQUEST:
                ok,reason=self._block("completion_token_limit_exceeded")
                return ok,reason,None
            reserved_total=prompt_estimate+completion_requested
            projected_tokens=self.total_tokens+reserved_total
            if projected_tokens>MAX_TOTAL_TOKENS:
                ok,reason=self._block("total_token_budget_exceeded")
                return ok,reason,None
            reserved_cost=_cost(prompt_estimate,completion_requested)
            if reserved_cost>MAX_COST_PER_REQUEST_USD:
                ok,reason=self._block("per_request_cost_budget_exceeded")
                return ok,reason,None
            if self.estimated_cost_usd+reserved_cost>MAX_COST_USD:
                ok,reason=self._block("total_cost_budget_exceeded")
                return ok,reason,None

            # Reserve the conservative maximum before contacting the provider.
            # This keeps the total budget enforceable even if a streaming provider
            # omits usage metadata.
            self.request_count+=1
            self.prompt_tokens+=prompt_estimate
            self.completion_tokens+=completion_requested
            self.total_tokens+=reserved_total
            self.estimated_cost_usd+=reserved_cost
            reservation={
                "prompt_tokens":prompt_estimate,
                "completion_tokens":completion_requested,
                "total_tokens":reserved_total,
                "cost_usd":reserved_cost,
            }
            self._persist()
            return True,"",reservation

    def record_usage(self,usage,reservation):
        if MODE!="PROXY" or usage is None or reservation is None:
            return
        prompt,completion,total=usage
        prompt=max(0,prompt)
        completion=max(0,completion)
        total=max(0,total)
        actual_cost=_cost(prompt,completion)
        with self.lock:
            # Never refund a reservation. Only charge any provider usage above
            # the conservative amount already reserved at preflight.
            self.prompt_tokens+=max(0,prompt-int(reservation["prompt_tokens"]))
            self.completion_tokens+=max(0,completion-int(reservation["completion_tokens"]))
            self.total_tokens+=max(0,total-int(reservation["total_tokens"]))
            self.estimated_cost_usd+=max(0,actual_cost-float(reservation["cost_usd"]))
            if prompt>MAX_PROMPT_TOKENS_PER_REQUEST:
                self._block("actual_prompt_token_limit_exceeded")
                return
            if completion>MAX_COMPLETION_TOKENS_PER_REQUEST:
                self._block("actual_completion_token_limit_exceeded")
                return
            if actual_cost>MAX_COST_PER_REQUEST_USD:
                self._block("actual_per_request_cost_budget_exceeded")
                return
            if self.total_tokens>MAX_TOTAL_TOKENS:
                self._block("actual_total_token_budget_exceeded")
                return
            if self.estimated_cost_usd>MAX_COST_USD:
                self._block("actual_total_cost_budget_exceeded")
                return
            self._persist()

BUDGET=BudgetState()

class Handler(BaseHTTPRequestHandler):
    mock_calls=0

    def log_message(self,fmt,*args):
        print("[gateway] "+(fmt % args),file=sys.stderr,flush=True)

    def _json(self,status,payload):
        data=json.dumps(payload).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type","application/json")
        self.send_header("Content-Length",str(len(data)))
        self.end_headers()
        self.wfile.write(data)

    def _auth_ok(self):
        return bool(LOCAL_TOKEN) and self.headers.get("Authorization","")==f"Bearer {LOCAL_TOKEN}"

    def do_GET(self):
        path=self.path.split("?",1)[0].rstrip("/")
        if path in ("","/health"):
            self._json(200,{"status":"ok","mode":MODE,"budget":BUDGET.snapshot()})
            return
        self._json(404,{"error":"not_found"})

    def do_POST(self):
        if not self._auth_ok():
            self._json(401,{"error":{"message":"invalid local gateway token","type":"invalid_api_key"}})
            return
        path=self.path.split("?",1)[0]
        if path not in ("/v1/chat/completions","/chat/completions","/completions"):
            self._json(404,{"error":{"message":"unsupported path","type":"not_found"}})
            return
        try:
            length=int(self.headers.get("Content-Length","0"))
        except ValueError:
            length=0
        if length<0 or length>MAX_BODY:
            self._json(413,{"error":{"message":"request too large","type":"invalid_request_error"}})
            return
        raw=self.rfile.read(length)
        try:
            body=json.loads(raw or b"{}")
        except json.JSONDecodeError:
            self._json(400,{"error":{"message":"invalid json","type":"invalid_request_error"}})
            return

        ok,reason,reservation=BUDGET.preflight(body)
        if not ok:
            self._json(429,{"error":{"message":reason,"type":"budget_exceeded","code":reason}})
            return

        if MODE=="MOCK":
            self._mock(body)
        elif MODE=="PROXY":
            self._proxy(raw)
        else:
            self._json(500,{"error":{"message":"invalid gateway mode","type":"server_error"}})

    def _is_ping(self,body):
        if body.get("max_tokens")!=1:
            return False
        msgs=body.get("messages")
        if not isinstance(msgs,list) or len(msgs)!=1:
            return False
        content=msgs[0].get("content") if isinstance(msgs[0],dict) else None
        if isinstance(content,list):
            content="".join(
                p.get("text","") for p in content
                if isinstance(p,dict) and p.get("type")=="text"
            )
        return isinstance(content,str) and content.strip()=="ping"

    def _mock_message(self,body):
        model=body.get("model") or "mock"
        if self._is_ping(body):
            return {
                "id":"chatcmpl-ping","object":"chat.completion","created":int(time.time()),
                "model":model,
                "choices":[{"index":0,"message":{"role":"assistant","content":"pong"},"finish_reason":"stop"}],
                "usage":{"prompt_tokens":1,"completion_tokens":1,"total_tokens":2},
            }
        Handler.mock_calls+=1
        if Handler.mock_calls==1:
            message={
                "role":"assistant",
                "content":"",
                "tool_calls":[{
                    "id":"call_asset_factory_001",
                    "type":"function",
                    "function":{"name":"terminal","arguments":json.dumps({
                        "security_risk":"LOW",
                        "summary":"Create isolated sandbox artifact and tests",
                        "command":BUILD_COMMAND,
                    })},
                }],
            }
            finish="tool_calls"
        else:
            message={"role":"assistant","content":"OPENHANDS_SANDBOX_BUILD_COMPLETE"}
            finish="stop"
        return {
            "id":f"chatcmpl-mock-{Handler.mock_calls}",
            "object":"chat.completion",
            "created":int(time.time()),
            "model":model,
            "choices":[{"index":0,"message":message,"finish_reason":finish}],
            "usage":{"prompt_tokens":20,"completion_tokens":10,"total_tokens":30},
        }

    def _mock(self,body):
        payload=self._mock_message(body)
        if not body.get("stream"):
            self._json(200,payload)
            return
        choice=payload["choices"][0]
        msg=choice["message"]
        base={
            "id":payload["id"],
            "object":"chat.completion.chunk",
            "created":payload["created"],
            "model":payload["model"],
        }
        chunks=[]
        if msg.get("tool_calls"):
            chunks.append({**base,"choices":[{"index":0,"delta":{"role":"assistant"},"finish_reason":None}]})
            for idx,tc in enumerate(msg["tool_calls"]):
                fn=tc["function"]
                chunks.append({**base,"choices":[{"index":0,"delta":{"tool_calls":[{
                    "index":idx,"id":tc["id"],"type":"function",
                    "function":{"name":fn["name"],"arguments":""},
                }]},"finish_reason":None}]})
                if fn.get("arguments"):
                    chunks.append({**base,"choices":[{"index":0,"delta":{"tool_calls":[{
                        "index":idx,"function":{"arguments":fn["arguments"]},
                    }]},"finish_reason":None}]})
        else:
            chunks.append({**base,"choices":[{"index":0,"delta":{"role":"assistant","content":msg.get("content","")},"finish_reason":None}]})
        chunks.append({**base,"choices":[{"index":0,"delta":{},"finish_reason":choice["finish_reason"]}]})
        self.send_response(200)
        self.send_header("Content-Type","text/event-stream")
        self.send_header("Cache-Control","no-cache")
        self.end_headers()
        for chunk in chunks:
            self.wfile.write(("data: "+json.dumps(chunk)+"\n\n").encode("utf-8"))
        if (body.get("stream_options") or {}).get("include_usage"):
            usage={**base,"choices":[],"usage":payload.get("usage") or {
                "prompt_tokens":20,"completion_tokens":10,"total_tokens":30
            }}
            self.wfile.write(("data: "+json.dumps(usage)+"\n\n").encode("utf-8"))
        self.wfile.write(b"data: [DONE]\n\n")
        self.wfile.flush()

    def _proxy(self,raw):
        if not UPSTREAM_BASE_URL or not UPSTREAM_API_KEY:
            self._json(503,{"error":{"message":"upstream not configured","type":"server_error"}})
            return
        url=UPSTREAM_BASE_URL+"/chat/completions"
        req=urllib.request.Request(
            url,
            data=raw,
            headers={
                "Content-Type":"application/json",
                "Authorization":f"Bearer {UPSTREAM_API_KEY}",
            },
            method="POST",
        )
        try:
            with urllib.request.urlopen(req,timeout=120) as resp:
                data=resp.read()
                content_type=resp.headers.get("Content-Type","application/json")
                BUDGET.record_usage(_usage_from_bytes(data,content_type),reservation)
                self.send_response(resp.status)
                self.send_header("Content-Type",content_type)
                self.send_header("Content-Length",str(len(data)))
                self.end_headers()
                self.wfile.write(data)
        except urllib.error.HTTPError as exc:
            data=exc.read()
            self.send_response(exc.code)
            self.send_header("Content-Type",exc.headers.get("Content-Type","application/json"))
            self.send_header("Content-Length",str(len(data)))
            self.end_headers()
            self.wfile.write(data)
        except Exception as exc:
            self._json(502,{"error":{"message":str(exc),"type":"gateway_error"}})

if __name__=="__main__":
    port=int(os.environ.get("PORT","9999"))
    server=ThreadingHTTPServer(("0.0.0.0",port),Handler)
    print(f"OpenHands gateway ready on :{port} mode={MODE}",flush=True)
    server.serve_forever()
